version: '3.1'
networks:
  app:
    driver: bridge

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'
    networks:
      - app

  back:
    container_name: back
    restart: unless-stopped
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./Dockerfile_back
    ports:
      - "5000:5000"
    volumes:
      - "./back:/back"
    networks:
      - app

  bot:
    container_name: bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile_bot
    volumes:
      - "./bot:/bot"
      - "./back/uploads:/uploads"
    networks:
      - app

  redis:
    container_name: redis
    image: redis:6.0-alpine
    expose:
      - 6379
    volumes:
      - "./redis:/data"
    command:
      - 'redis-server'
      - '--requirepass pass'
    networks:
      - app